services:
  products:
    build: ./products-service
    ports: ["3001:3001"]
    environment:
      PORT: 3001
  inventory:
    build: ./inventory-service
    ports: ["3002:3002"]
    environment:
      PORT: 3002
  orders:
    build: ./orders-service
    ports: ["3003:3003"]
    environment:
      PORT: 3003
      INVENTORY_URL: http://inventory:3002
    depends_on:
      inventory:
        condition: service_started
